services:
- docker
env:
- DIST=ubuntu-14.04 CHEFVER=13.10.0
- DIST=ubuntu-14.04 CHEFVER=14.3.37
- DIST=ubuntu-16.04 CHEFVER=13.10.0
- DIST=ubuntu-16.04 CHEFVER=14.3.37
- DIST=ubuntu-18.04 CHEFVER=13.10.0
- DIST=ubuntu-18.04 CHEFVER=14.3.37
- DIST=debian-8 CHEFVER=13.10.0
- DIST=debian-8 CHEFVER=14.3.37
- DIST=debian-9 CHEFVER=13.10.0
- DIST=debian-9 CHEFVER=14.3.37
- DIST=centos-6 CHEFVER=13.10.0
- DIST=centos-6 CHEFVER=14.3.37
- DIST=centos-7 CHEFVER=13.10.0
- DIST=centos-7 CHEFVER=14.3.37
- DIST=amazonlinux CHEFVER=13.10.0
- DIST=amazonlinux CHEFVER=14.3.37
- DIST=amazonlinux-2 CHEFVER=14.3.37
language: ruby
rvm:
- 2.3
cache:
- bundler
install:
- travis_wait 30 bundle install --jobs=3 --retry=3 --deployment
script:
- bash travis-build.sh
notifications:
  slack:
    secure: JJvnLuZ15PY4scgBaa863rKdFWalqQhaZVk5dtQWPbR0iYRG+8AW21ojJps9i1evUfFe1wT1qczbJjp/B/WE544lEga6qai7/7H/YO9HlL8zMZOjGFmjVvoEhl5+SRjOfW3KWZizTpsJ5fvh3aCxobSy+olzH6ZjIw1K781JYpQ=
